import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Hero, Navbar } from "./components";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="./favicon1.ico" sizes="any" />
      <link
        rel="icon"
        href="/icon?<generated>"
        type="image/<generated>"
        sizes="<generated>"
      />
      <link
        rel="apple-touch-icon"
        href="/apple-icon?<generated>"
        type="image/<generated>"
        sizes="<generated>"
      />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative z-0 bg-[#050816]">
          <div className="bg-[url(./assets/herobg.png)] bg-cover bg-no-repeat bg-center cursor-pointer">
            <Navbar />
            <Hero />
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
